[settings]
python.venv_stdlib = true

[tools]
python = "3.11"

[env]
_.file = ".env"
_.python.venv = { path = ".venv", create = true }
PROJECT_NAME = "{{ config_root | basename }}"

[tasks.install]
alias = "i"
depends = "install:*"

[tasks.lint]
alias = "l"
depends = "lint:*"

[tasks.pre-commit]
depends = ["lint:format"]

[tasks.pre-push]
depends = ["lint:blender-extension"]

[tasks.format]
depends = "install:requirements"
sources = ["**/*.py"]
run = "black ."

[tasks.build]
depends = "lint:blender-extension"
sources = ["src/**/*"]
run = '''
#!/bin/bash
mkdir -p build
rm -rf build/*
'{{ env.BLENDER_BIN }}' --command extension build --source-dir src --output-dir build
'''

[tasks."lint:blender-extension"]
sources = [".env", "src/blender_manifest.toml"]
shell = "bash -c"
run = "'{{ env.BLENDER_BIN }}' --command extension validate src"

[tasks."lint:format"]
depends = "install:requirements"
sources = ["**/*.py"]
run = "black --check ."

[tasks."install:blender-extension-symlink"]
env.LINK_PATH = "\"{{ env.BLENDER_EXTENSION_REPO }}/{{ env.PROJECT_NAME }}\""
env.SRC_PATH = "\"{{ [config_root] | concat(with='src') | join_path }}\""
shell = "bash -c"
run = "ln -s {{ env.SRC_PATH }} {{ env.LINK_PATH }}"
run_windows = "pwsh -c 'New-Item -ItemType SymbolicLink -Path {{ env.LINK_PATH }} -Value {{ env.SRC_PATH }} -Force'"

[tasks."install:requirements"]
sources = ["requirements-dev.txt"]
run = "pip install -r requirements-dev.txt"

[tasks."install:git-hooks"]
run = [
	"mise generate git-pre-commit --write --hook pre-commit --task pre-commit",
	"mise generate git-pre-commit --write --hook pre-push --task pre-push"
]
