[settings]
python.venv_stdlib = true

[tools]
python = "3.11"

[env]
_.file = ".env"
_.python.venv = { path = ".venv", create = true }

[tasks.install]
alias = "i"
depends = "install:*"

[tasks.lint]
alias = "l"
depends = "lint:*"

[tasks.pre-commit]
depends = "install:requirements"
run = "black --check ."

[tasks.format]
depends = "install:requirements"
sources = ["**/*.py"]
run = "black ."

[tasks.build]
depends = "lint:blender-extension"
sources = ["src/**/*"]
run = '''
#!/bin/bash
mkdir -p build
rm -rf build/*
'{{ env.BLENDER_BIN }}' --command extension build --source-dir src --output-dir build
'''

[tasks."lint:blender-extension"]
sources = [".env", "src/blender_manifest.toml"]
shell = "bash -c"
run = "'{{ env.BLENDER_BIN }}' --command extension validate src"

[tasks."install:requirements"]
sources = ["requirements-dev.txt"]
run = "pip install -r requirements-dev.txt"

[tasks."install:git-hooks"]
run = "mise generate git-pre-commit --write"
